# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - microblog-stage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://microblog.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_29588c061cad496e9e960a281d8affbc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fb2ca6fc08d542728d2ddc87da240868 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: microblog.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_29588c061cad496e9e960a281d8affbc }}/microblog:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'microblog-stage'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_86540643e8cd4ad3b41131a66f61c28e }}
        images: 'microblog.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_29588c061cad496e9e960a281d8affbc }}/microblog:${{ github.sha }}'